name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Java JDK 11 usando setup-java v3 y especificar distribution explícitamente
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'openjdk'

      # Compilar el proyecto usando Maven
      - name: Build with Maven
        run: mvn clean install

      # Ejecutar el código Java
      - name: Run Java program
        run: java -cp target/classes Sum
