name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar Java JDK 11 usando setup-java v3 y especificar distribution explícitamente
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      # Compilar el proyecto usando Maven
      - name: Build with Maven
        run: mvn clean install

      # Ejecutar el código Java
      - name: Run Java program
        run: java -cp bin Sum
