name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar Java JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Compilar el proyecto usando Maven (puedes usar Gradle si prefieres)
      - name: Build with Maven
        run: mvn clean install

      # Ejecutar el código Java (solo para asegurarnos de que funcione correctamente)
      - name: Run Java program
        run: java -cp target/classes Sum
